spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    schema: classpath:import.sql
mybatis:
  config-location: classpath:mybatis-config.xml

---
spring.profiles: local
spring:
  h2:
    console:
      enabled: true
      path: /h2-console #jdbc URL : jdbc:h2:mem:testdb
---
spring.profiles: dev
spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/ohmyplay
    username: test
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
server.port: 80
---
spring.profiles: product
spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/ohmyplay
    username: test
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
server.port: 80